#!/usr/bin/env python3
"""
Auto-Update Index Files Script
Automatically scans folders and updates index.html with all HTML files found
Run this script whenever you add new files - no manual editing needed!
"""

import os
import re
from pathlib import Path

# All category folders
CATEGORIES = [
    "Neurology",
    "Cancer",
    "Eyes-ophthalmology",
    "Infectious-disease",
    "Paeds",
    "Mental-health",
    "Cardio-respiratory",
    "General",
    "Women's-Health",
    "Men's-Health",
    "Endocrine-metabolic",
    "GI-Gastroenterology-hepatology",
    "Skin-and-Nail",
    "ENT-and-Oral-health",
    "MSK-and-Rheumatology",
    "Pregnancy",
    "Renal-Urology",
    "Haematology",
    "Allergy",
    "Palliative",
    "Geriatrics"
]

def clean_title(filename):
    """Convert filename to readable title"""
    # Remove .html extension
    title = filename.replace('.html', '')
    
    # Replace underscores and hyphens with spaces
    title = title.replace('_', ' ').replace('-', ' ')
    
    # Capitalize each word
    title = ' '.join(word.capitalize() for word in title.split())
    
    return title

def get_html_files(folder_path):
    """Get all HTML files in folder except index.html"""
    html_files = []
    
    if not os.path.exists(folder_path):
        return html_files
    
    for file in os.listdir(folder_path):
        if file.endswith('.html') and file.lower() != 'index.html':
            html_files.append(file)
    
    # Sort alphabetically
    html_files.sort()
    
    return html_files

def create_topics_array(html_files):
    """Create JavaScript array from HTML files"""
    if not html_files:
        return "[]"
    
    topics = []
    for file in html_files:
        title = clean_title(file)
        # Escape quotes in filename and title
        safe_file = file.replace('"', '\\"')
        safe_title = title.replace('"', '\\"')
        topics.append(f'    {{ file: "{safe_file}", title: "{safe_title}" }}')
    
    return "[\n" + ",\n".join(topics) + "\n  ]"

def update_index_html(folder_name, display_name, topics_array):
    """Update or create index.html with auto-populated topics"""
    
    html_content = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{display_name} - Medical Reference</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    max-width: 900px;
    margin: 2rem auto;
    padding: 0 1rem;
    line-height: 1.6;
  }}
  h1 {{
    color: #2c3e50;
    border-bottom: 3px solid #3498db;
    padding-bottom: 0.5rem;
  }}
  .back-link {{
    display: inline-block;
    margin-bottom: 1rem;
    color: #3498db;
    text-decoration: none;
    font-weight: 500;
  }}
  .back-link:hover {{
    text-decoration: underline;
  }}
  ul {{
    list-style: none;
    padding: 0;
  }}
  li {{
    margin: 0.8rem 0;
    padding: 0.8rem;
    background: #f8f9fa;
    border-left: 4px solid #3498db;
    border-radius: 4px;
  }}
  li:hover {{
    background: #e9ecef;
  }}
  a {{
    color: #2c3e50;
    text-decoration: none;
    font-size: 1.1rem;
  }}
  a:hover {{
    color: #3498db;
  }}
  .empty-state {{
    text-align: center;
    padding: 3rem;
    color: #6c757d;
    font-style: italic;
  }}
  .count {{
    color: #6c757d;
    font-size: 0.9rem;
    margin-left: 0.5rem;
  }}
</style>
</head>
<body>
<a href="../index.html" class="back-link">← Back to Main Library</a>
<h1>{display_name}</h1>
<div id="content">
  <p class="empty-state">Loading topics...</p>
</div>

<script>
// Auto-generated by update_indexes.py script
// DO NOT MANUALLY EDIT - Changes will be overwritten
async function loadTopics() {{
  const topics = {topics_array};
  
  const contentDiv = document.getElementById('content');
  
  if (topics.length === 0) {{
    contentDiv.innerHTML = '<p class="empty-state">No topics added yet. Add your HTML files to this folder.</p>';
    return;
  }}
  
  let html = '<p class="count">Found ' + topics.length + ' topic' + (topics.length === 1 ? '' : 's') + '</p>';
  html += '<ul>';
  topics.forEach(topic => {{
    const safeHref = encodeURIComponent(topic.file);
    html += `<li><a href="${{safeHref}}">${{topic.title}}</a></li>`;
  }});
  html += '</ul>';
  
  contentDiv.innerHTML = html;
}}

loadTopics();
</script>
</body>
</html>'''
    
    file_path = os.path.join(folder_name, "index.html")
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(html_content)

def main():
    """Main function to update all indexes"""
    print("=" * 70)
    print("Auto-Update Index Files Script")
    print("=" * 70)
    print()
    print("Scanning folders for HTML files...\n")
    
    total_files = 0
    updated_folders = 0
    
    for category in CATEGORIES:
        folder_name = category.replace(" ", "-").replace("&", "and")
        display_name = category.replace("-", " ").replace("and", "&")
        
        # Get HTML files in this folder
        html_files = get_html_files(folder_name)
        
        if html_files:
            print(f"📁 {display_name}")
            print(f"   Found {len(html_files)} file(s):")
            for file in html_files:
                print(f"   ✓ {file}")
            
            # Create topics array
            topics_array = create_topics_array(html_files)
            
            # Update index.html
            update_index_html(folder_name, display_name, topics_array)
            print(f"   ✅ Updated {folder_name}/index.html")
            print()
            
            total_files += len(html_files)
            updated_folders += 1
        else:
            print(f"📁 {display_name}: No files found (skipped)")
    
    print("=" * 70)
    print(f"✅ Complete!")
    print(f"   Updated {updated_folders} folders")
    print(f"   Found {total_files} total HTML files")
    print("=" * 70)
    print()
    print("Next steps:")
    print("1. Check the updated index.html files in each folder")
    print("2. Commit and push to GitHub:")
    print("   git add .")
    print("   git commit -m 'Auto-update all index files'")
    print("   git push")
    print()
    print("💡 Tip: Run this script whenever you add new HTML files!")
    print()

if __name__ == "__main__":
    main()